---
- type: java\.time\.LocalDateTime
  specAsParameter:
    - type: string
      format: date
- type: java\.time\.LocalDate
  specAsParameter:
    - type: string
      format: date
- type: java\.time\.LocalTime
  specAsParameter:
    - type: string
      format: date
- type: java\.time\.ZonedDateTime
  specAsParameter:
    - type: string
      format: date
