---
- type: java\.time\.LocalDateTime
  specAsParameter:
    - type: string
      format: date
- type: java\.time\.LocalDate
  specAsParameter:
    - type: string
      format: date
- type: java\.time\.LocalTime
  specAsParameter:
    - type: string
      format: date
- type: java\.time\.ZonedDateTime
  specAsParameter:
    - type: string
      format: date
- type: models\.GameActions\.CellAction
  specAsParameter:
    - type: string
    - enum:
      - reveal
      - set-question-flag
      - set-red-flag
      - clean
- type: models\.GameActions\.GameStateAction
  specAsParameter:
    - type: string
    - enum:
      - pause
      - resume
